name: JoanWiden
favicon: null
layout_spectrum: 0.4156312805134803
typography_spectrum: 0.8435551095753908
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffe'
    - '#656aa2'
    - '#544192'
    - '#858ec5'
    - '#cecfd8'
  brandStrength: 0
  lightness: 0.13994467165321112
  saturation: 0.18694620579481125
  rhythmicContrast: 0.9100405967328697
purpose: []
